In [5]:
import json

data = []
endata = []
chdata = []

for line in open('test.txt', 'r', encoding='utf-8'):
    # val = re.sub(r,' ',line)
    data.append(json.loads(line))  
    
print('----------')

for i in range(len(data)):
    endata.append(data[i]['english'])
    chdata.append('@'+data[i]['chinese']+'。')

en_vocab = set(''.join(endata))
id2en = list(en_vocab)
en2id = {c:i for i,c in enumerate(id2en)}

# 分別生成中英文字典
ch_vocab = set(''.join(chdata))
id2ch = list(ch_vocab)
ch2id = {c:i for i,c in enumerate(id2ch)}

print('\n中文數據:\n', chdata)


----------

中文數據:
 ['@为了更好的锐度，但是附带的会多一些颗粒度，可以使用这个显影剂的1：1稀释液。。', '@他还把宣扬自己思想的所谓《绿皮书》称作“新福音书”。。', '@微风推着我去爱抚它的长耳朵。', '@它们的先烈们的鲜血是白流了…。', '@最后，在1月31日，湖人将前往汽车城底特律挑战活塞队，活塞近来在东部排名第二。。', '@“真是天造地设的一对——我父亲喜欢结交名人，杰姬酷爱金钱，”亚历山大在婚礼上讥讽道。他和克里斯蒂娜从未同他们的继母和睦相处过。。', '@2006年，沃尔玛的推荐引擎竟将《人猿星球》与马丁·路德·金的记录片配成了一对，为此沃尔玛遭到了种族歧视的指控。。', '@通过电子探针显微分析确定贫化渣中主要铜相为冰铜相。。', '@吉姆靠给人擦皮鞋为生。。']


In [6]:
en_num_data = [[en2id[en] for en in line ] for line in endata]
ch_num_data = [[ch2id[ch] for ch in line] for line in chdata]
de_num_data = [[ch2id[ch] for ch in line][1:] for line in chdata]

print('char:', endata[1])
print('index:', en_num_data[1])
print(len(en_num_data))
len(ch_num_data)
# de_num_data

char: He calls the Green Book, his book of teachings, “the new gospel.
index: [30, 54, 18, 40, 6, 35, 35, 33, 18, 9, 43, 54, 18, 12, 0, 54, 54, 39, 18, 37, 59, 59, 27, 51, 18, 43, 58, 33, 18, 29, 59, 59, 27, 18, 59, 49, 18, 9, 54, 6, 40, 43, 58, 39, 3, 33, 51, 18, 1, 9, 43, 54, 18, 39, 54, 32, 18, 3, 59, 33, 20, 54, 35, 10]
9


9

In [7]:
import numpy as np

max_encoder_seq_length = max([len(txt) for txt in en_num_data])
max_decoder_seq_length = max([len(txt) for txt in ch_num_data])
print('max encoder length:', max_encoder_seq_length)
print('max decoder length:', max_decoder_seq_length)

# 將數據進行onehot處理
encoder_input_data = np.zeros((len(en_num_data), max_encoder_seq_length, len(en2id)), dtype='float32')
decoder_input_data = np.zeros((len(ch_num_data), max_decoder_seq_length, len(ch2id)), dtype='float32')
decoder_target_data = np.zeros((len(ch_num_data), max_decoder_seq_length, len(ch2id)), dtype='float32')

for i in range(len(ch_num_data)):
    for t, j in enumerate(en_num_data[i]):
        encoder_input_data[i, t, j] = 1.
    for t, j in enumerate(ch_num_data[i]):
        decoder_input_data[i, t, j] = 1.
    for t, j in enumerate(de_num_data[i]):
        decoder_target_data[i, t, j] = 1.

print('index data:\n', en_num_data[1])
print('one hot data:\n', encoder_input_data[1])

max encoder length: 165
max decoder length: 65
index data:
 [30, 54, 18, 40, 6, 35, 35, 33, 18, 9, 43, 54, 18, 12, 0, 54, 54, 39, 18, 37, 59, 59, 27, 51, 18, 43, 58, 33, 18, 29, 59, 59, 27, 18, 59, 49, 18, 9, 54, 6, 40, 43, 58, 39, 3, 33, 51, 18, 1, 9, 43, 54, 18, 39, 54, 32, 18, 3, 59, 33, 20, 54, 35, 10]
one hot data:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
